# Generated by Django 3.1.6 on 2021-02-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pee', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('N', '')], max_length=12, null=True, verbose_name='Went Pee')),
                ('poo', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('N', '')], max_length=12, null=True, verbose_name='Went Poo')),
                ('sleep', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('N', '')], max_length=12, null=True, verbose_name='Went to Sleep')),
                ('awoke', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('N', '')], max_length=12, null=True, verbose_name='Woke Up')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Datetime')),
            ],
        ),
    ]
