# Generated by Django 3.1.6 on 2021-02-11 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='accident',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No'), ('N', '')], max_length=12, null=True, verbose_name='Accident'),
        ),
    ]
