# Generated by Django 3.1.6 on 2021-02-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_record_accident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='accident',
            field=models.BooleanField(default=False, verbose_name='Accident'),
        ),
        migrations.AlterField(
            model_name='record',
            name='awoke',
            field=models.BooleanField(default=False, verbose_name='Woke Up'),
        ),
        migrations.AlterField(
            model_name='record',
            name='pee',
            field=models.BooleanField(default=False, verbose_name='Went Pee'),
        ),
        migrations.AlterField(
            model_name='record',
            name='poo',
            field=models.BooleanField(default=False, verbose_name='Went Poo'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sleep',
            field=models.BooleanField(default=False, verbose_name='Went to Sleep'),
        ),
    ]
