# Generated by Django 3.1.6 on 2021-02-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210218_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='diarrhea',
            field=models.BooleanField(default=False, verbose_name='Had Diarrhead'),
        ),
    ]
